"""Команда ``create-migration``: каскадный autogenerate по лесенке тиров (от базового вниз)."""

from __future__ import annotations

import sys

from db_models.cli.create_migration.emptiness import is_empty_autogenerated_revision
from db_models.cli.create_migration.paths import ROOT
from db_models.cli.create_migration.revision import run_revision
from db_models.models import LADDER, Tier


def contours_from_start(start: Tier) -> tuple[Tier, ...]:
    idx = LADDER.index(start)
    return LADDER[idx:]


def main() -> None:
    """Точка входа: каскадный/ручной autogenerate, удаление пустых ревизий, регенерация стабов."""
    argv = sys.argv[1:]
    tier_names = "|".join(t.value for t in LADDER)
    if len(argv) < 3:
        print(
            f'Usage: create-migration <{tier_names}> "message" [--autogenerate|--manual]',
            file=sys.stderr,
        )
        sys.exit(2)

    raw_start = argv[0].strip().lower()
    try:
        start = Tier(raw_start)
    except ValueError:
        print(f"Unsupported environment: {raw_start!r}. Allowed: {[t.value for t in LADDER]}", file=sys.stderr)
        sys.exit(2)
    message = argv[1]
    mode = argv[2].strip().lower() if len(argv) > 2 else "--autogenerate"

    if mode not in ("--autogenerate", "--manual"):
        print(
            f"Unsupported mode: {mode!r}. Allowed: --autogenerate, --manual",
            file=sys.stderr,
        )
        sys.exit(2)

    autogenerate = mode == "--autogenerate"
    contours = contours_from_start(start) if autogenerate else (start,)

    for env in contours:
        print(f"Creating migration for {env} ({mode})")
        created = run_revision(env, message, autogenerate=autogenerate)
        if autogenerate and created is not None and is_empty_autogenerated_revision(created):
            print(f"Removing empty revision: {created.relative_to(ROOT)}", file=sys.stderr)
            created.unlink()

    print("Regenerating stubs...")
    from db_models.cli import generate_stubs  # noqa: PLC0415

    generate_stubs.main()


__all__ = ["main"]
