"""Определение «пустых» autogenerate-ревизий и поиск только что созданного файла ревизии."""

from __future__ import annotations

import ast
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pathlib import Path


def snapshot_py_files(directory: Path) -> dict[Path, float]:
    """Снимок mtime всех ``*.py`` в каталоге (пустой словарь, если каталога нет).

    :param directory: Каталог ревизий контура.
    :return: Отображение путь -> время модификации.
    """
    if not directory.is_dir():
        return {}
    return {p: p.stat().st_mtime for p in directory.glob("*.py")}


def find_created_revision(before: dict[Path, float], after: dict[Path, float]) -> Path | None:
    """Определить файл ревизии, появившийся (или изменённый) между двумя снимками.

    :param before: Снимок до запуска alembic.
    :param after: Снимок после запуска alembic.
    :return: Путь созданной ревизии либо ``None``, если однозначно определить не удалось.
    """
    new_paths = [p for p in after if p not in before]
    if len(new_paths) == 1:
        return new_paths[0]
    if len(new_paths) > 1:
        return max(new_paths, key=lambda p: after[p])
    changed = [p for p in after if p in before and after[p] > before[p]]
    if len(changed) == 1:
        return changed[0]
    return None


def upgrade_body_is_empty(func: ast.FunctionDef) -> bool:
    """Вернуть ``True``, если тело функции ``upgrade`` состоит только из ``pass``/docstring."""
    for stmt in func.body:
        if isinstance(stmt, ast.Pass):
            continue
        if isinstance(stmt, ast.Expr) and isinstance(stmt.value, ast.Constant) and isinstance(stmt.value.value, str):
            continue
        return False
    return True


def is_empty_autogenerated_revision(path: Path) -> bool:
    """Вернуть ``True``, если функция ``upgrade`` ревизии пуста (только ``pass``/docstring).

    :param path: Путь к файлу ревизии.
    :return: Признак пустой автоген-ревизии.
    """
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except (OSError, SyntaxError):
        return False
    for node in tree.body:
        if isinstance(node, ast.FunctionDef) and node.name == "upgrade":
            return upgrade_body_is_empty(node)
    return True
